[project]
name = "sf-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.25.0",
    "requests>=2.31.0",
    "xmltodict>=0.13.0",
    "python-dotenv>=1.0.0",
]
